import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "@/app/globals.css";
import { ReactNode } from "react";
import App from "@/components/layout/App";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: ReactNode;
}

export default async function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased`}>
        <App>{children}</App>
      </body>
    </html>
  );
}
